FROM python:3

ARG HOST=127.0.0.1
ARG PORT=8000
ARG VECTORSTORE=/opt/vectorstore

RUN mkdir -p ${VECTORSTORE}

WORKDIR  /opt/langserve
COPY . .

RUN apt install -y gcc && \
    pip3 install -r requirements.langclient.txt
CMD ["python3", "/opt/langserve/langclient.py", ${HOST}, ${PORT}, ${VECTORSTORE}]
