FROM python:3.10.13-bookworm

WORKDIR  /opt/langserve
COPY . .

ENV HOST=127.0.0.1
ENV PORT=8000
ENV VECTORSTORE=/opt/vectorstore

RUN mkdir -p ${VECTORSTORE}

RUN apt update && \
    apt install -y gcc

RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.langclient.txt

EXPOSE ${PORT}

ENTRYPOINT ["/bin/bash", "-c", "python3 /opt/langserve/langclient.py ${HOST} ${PORT} ${VECTORSTORE}"]
